# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopoverDemo1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopoverDemo1
	pod 'Kingfisher', '7.2.4'

  target 'PopoverDemo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
